### ISSUE TITLE
Instructions on readme page inconsistent.

### ISSUE THREAD

**Issue by jfcaron3** [dtdannen/dcss-ai-wrapper#3]
The instructions on the readme page of this github repo are inconsistent in the usage of python 2 and 3.  Also the instructions in "How to Run an agent in the terminal" do not seem to work, as some paths are hardcoded in to the start*.sh scripts and in the rl_sonja_sprint_demo.py script.  

I suggest someone who is interested in getting external users to try this out should update the instructions to all use a single relative path, and with a single version of python.

**Comment by jfcaron3** [comment]
Here are the first and last 200 lines of the output when I try to run ./start_crawl_terminal_dungeon.sh from the "How to Run an agent in the terminal" section:
[output_trunc.log](https://github.com/dtdannen/dcss-ai-wrapper/files/4440457/output_trunc.log)

**Comment by dtdannen** [comment]
Significant progress has been made on the README so I'm deleting this issue for now (for example, python 2 is no longer needed and all paths are relative now).

**Comment by gregs-git** [comment]
Running from the terminal - eventually realised I needed to be in the virtual env to get things started running main.py. Maybe add this to the section? 

Anyone jumping to this bit of the README as I did might need a prompt here to start the venv, then run main.py. Even though I did install the packages via requirement.txt, I still forgot later!
